### PR TITLE
Migrate to Monger

### PR DESCRIPTION
**Pull request by michaelklishin**
Basically, shit compiles and nothing obvious breaks:
- Pastes can be created
- Pastes can be viwed
- Pastes can be listed
- Private pastes can be created
- Private pastes can be viewed
- I fixed a minor libnoir migration issue (an outdated require had to be removed)

I am not smart enough to figure out how to get Browser ID work with localhost or where in the UI I can delete a paste but everything was straightforward enough. Please test how the new session store works and if we need to purge the old sessions collection data (I am not sure if `monger.ring.session-store` store works the way the old one does).

Along the way, 3 dependencies are gone: mongo-store, exploding fish, congomongo, all replaced by Monger and what it has out of the box.

There were some minor code changes to work around `monger.collection/insert` behavior (it does not return a map, instead, it returns a write result). I will probably add a new function that will work as CongoMongo's insert
and we can migrate to it.

I also noticed that there is a bunch of places that could dearly benefit from using [Validateur](https://github.com/michaelklishin/validateur). We can migrate to it later.

So, shit mostly works and if something doesn't, I blame it on the lack of a test suite. My codez are obviously perfect.

What are you waiting for? Press that "Merge This Pull Reques" button, now!

### CODE REVIEW

**Comment by Raynes** [comment]
Looks good. My only question is why do you have to create object ids manually when inserting new records? If it is necessary, wouldn't it be useful to have a wrapper function in `monger.collection` or something? It seems annoying to have to pull in that java class every time you want to insert a record.

**Comment by Raynes** [comment]
Regarding validations, lib-noir has some built in validation middleware that can also be considered. But yeah, definitely need a validation lib.

**Comment by michaelklishin** [comment]
Object id will be generated for you but MongoDB Java driver then tries to mutate the document object that's being inserted
and it does not work very well with Clojure or libraries that sit on top of the driver and convert DBObjects into, say, Clojure data structures.

So, it is only necessary for cases when you want the generated id back. Monger 1.1 will have some kind of solution, I am not sure what's the best way yet. A new function, probably.

**Comment by Raynes** [comment]
Oh, Monger's `insert` returns the write result and not what it wrote. Now I get what you were saying.

On that note, what is the rationale for `insert` doing that?

(Fwiw, I'm just curious. I'm definitely going to take the pull request. I just want to understand things first. :))

**Comment by michaelklishin** [comment]
There is no rationale, I just had no idea what I am doing with this Clojure thing 1 year ago when Monger was started.

**Comment by Raynes** [comment]
Heh.

So making `insert` return what it inserted would remove the need to create object ids like this, right?

**Comment by michaelklishin** [comment]
Correct. I don't want to break existing users' code, though (including my own), so I am thinking about adding `monger.collection/insert-map` or `monger.collection/insert-and-return`. The former reflects other API parts where functions that end in `-map` return Clojure data structures and others are low level and return Java objects that are very rarely needed. But it is not very descriptive. The latter is descriptive but sounds a little silly. But hey, it's a monger and mongers are not known for being logical.

**Comment by Raynes** [comment]
Heh. Okay, that's all I've got for now. I'm about to take off so I can't test right now, but I'll work on it tonight. :)

Thanks for the hard work!

**Pull request merged**
