### PR TITLE
Fix python and perl extensions

### PR DESCRIPTION
**Pull request by mrshankly**
When using the api the python and perl extensions on the language field had to be `..py` and `..pl` in order to get the language properly identified.

### CODE REVIEW

**Comment by Raynes** [comment]
Thanks! Will deploy this fix shortly.

**Comment by Raynes** [comment]
Deployed.

Also, if you're using the API for something non-private, I'd love to hear what you're doing with me. Hit me up if you want. :)

Cheers!

**Comment by mrshankly** [comment]
It's just a small script so I could easily create pastes when working remotely on a server. Here's the code, https://github.com/mrshankly/refheap-paste.

**Comment by Raynes** [comment]
Nice. I actually have something similar: https://github.com/Raynes/refh

**Comment by mrshankly** [comment]
Yeah, I thought that someone had already made something like this. It's just that I first looked at the api and realized how easy it would be to make it, so I just made it instead of searching for one. I'm going to give a look at yours, I'm learning haskell and all :).

**Comment by Raynes** [comment]
Yeah, nothing wrong with having two! Python is probably easier to use on non unix/OS X systems.

**Pull request merged**
